name: Deploy to PythonAnywhere

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        cd backend
        pip install -r requirements.txt
        
    - name: Run tests
      run: |
        cd backend
        python manage.py test --verbosity=2
        
    - name: Deploy to PythonAnywhere
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.PYTHONANYWHERE_HOST }}
        username: ${{ secrets.PYTHONANYWHERE_USERNAME }}
        key: ${{ secrets.PYTHONANYWHERE_SSH_KEY }}
        script: |
          # Navigate to project directory
          cd /home/${{ secrets.PYTHONANYWHERE_USERNAME }}/health_bridge_hospital
          
          # Pull latest changes from GitHub
          git pull origin main
          
          # Navigate to backend directory
          cd backend
          
          # Activate virtual environment
          source venv/bin/activate
          
          # Install/update dependencies
          pip install --user -r requirements.txt
          
          # Run database migrations
          python manage.py migrate
          
          # Collect static files
          python manage.py collectstatic --noinput
          
          # Create logs directory if it doesn't exist
          mkdir -p logs
          
          # Restart the web app
          touch /var/www/${{ secrets.PYTHONANYWHERE_USERNAME }}_pythonanywhere_com_wsgi.py
          
          echo "Deployment completed successfully!"
