name: Simple Deployment Check

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  check-deployment:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install backend dependencies
      run: |
        cd backend
        pip install -r requirements.txt
        
    - name: Test Django configuration
      run: |
        cd backend
        python manage.py check --settings=healthbridge_backend.settings
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install frontend dependencies
      run: npm ci
      
    - name: Build frontend
      run: npm run build
      
    - name: Deployment check passed
      run: |
        echo "✅ Backend configuration is valid"
        echo "✅ Frontend builds successfully"
        echo "✅ Ready for manual deployment"
